In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

In [2]:
train_data = pd.read_csv("train.csv")
train_data = train_data.drop(["id"], axis = 1)

In [3]:
train_data.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [4]:
train_data['TyreLife'] = train_data['TyreLife'].astype('int64')
train_data['Position_Change'] = train_data['Position_Change'].astype('int64')
train_data['PitNextLap'] = train_data['PitNextLap'].astype('int64')

In [5]:
feature_cols = [col for col in train_data.columns if col != "PitNextLap"]

In [6]:
X = train_data.drop('PitNextLap', axis = 1)
y = train_data['PitNextLap']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, stratify = y, random_state = 42
)

In [8]:
num_cols = X_train.select_dtypes(include=np.number).columns.tolist()

cat_cols = X_train.select_dtypes(exclude=np.number).columns.tolist()

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: ['Year', 'PitStop', 'LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', 'Position_Change']
Categorical columns: ['Driver', 'Compound', 'Race']

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(handle_unknown='ignore'), cat_cols)], remainder='passthrough')
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [10]:
X_train

<351312x906 sparse matrix of type '<class 'numpy.float64'>'
	with 4479232 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(
    n_estimators = 100,
    criterion='gini',
    random_state = 42,
    class_weight='balanced',
    bootstrap = True,
    oob_score = True
)

classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', oob_score=True, random_state=42)

In [12]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 1 0 ... 0 0 0]

In [13]:
y_prob = classifier.predict_proba(X_test)[:, 1]
print(y_prob)

[0.02 0.69 0.   ... 0.02 0.04 0.47]

In [14]:
from sklearn.metrics import roc_auc_score

print("AUC-ROC:", roc_auc_score(y_test, y_prob))

AUC-ROC: 0.9411093315805326

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93     70352
           1       0.75      0.68      0.72     17476

    accuracy                           0.89     87828
   macro avg       0.84      0.81      0.83     87828
weighted avg       0.89      0.89      0.89     87828

Confusion Matrix:
[[66449  3903]
 [ 5528 11948]]

In [16]:
test = pd.read_csv("test.csv")
test.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [17]:
test_ids = test['id']
test_data = test.drop(columns=['id'], axis = 1)
test_data.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [20]:
test_data['TyreLife'] = test_data['TyreLife'].astype('int64')
test_data['Position_Change'] = test_data['Position_Change'].astype('int64')

In [21]:
test_data = ct.transform(test_data)

In [22]:
predictions = classifier.predict_proba(test_data)[:, 1]

In [23]:
submission = pd.DataFrame({
    'id': test_ids,
    'PitNextLap': predictions
})

submission.to_csv('submission_random_forest_direct_predictions.csv', index=False)
print(submission.head())
print("Submission shape:", submission.shape)

       id  PitNextLap
0  439140        0.01
1  439141        0.01
2  439142        0.01
3  439143        0.14
4  439144        0.84
Submission shape: (188165, 2)

<hr>